apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-yjf6
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0021-tenant/tkrw-pr712-0075-0021-app/devfile-sample-yjf6@sha256:f94c9c768713f2f47b102398e55b32f81726d60edf9ee8ca29ded99c0c505d63
        name: my-nodejs
        resources: {}
status: {}
